### ISSUE TITLE
Arduino Pro Mini 

### ISSUE THREAD

**Issue by themuck** [richards-tech/RTIMULib-Arduino#10]
Hallo,
works this on a Arduino Pro Mini, is there a tutorial? I am not sure what i must do... i use a IMU 9250.

ok i copy the files the code compiles and i have massages on the Serial monitor, but where can i define the IMU 9250?

"ArduinoIMU starting using device MPU-9150
Failed to init IMU: -6"

IMU 6 is the 9250?

when in disconnect the IMU it says 

"ArduinoIMU starting using device MPU-9150
Failed to init IMU: -1"

**Comment by maziarzamani** [comment]
When it says "Failed to init IMU: -6", it means that it fails in the step where it returns -6, which is here. But you are using the 9150 library for the 9250?

**Comment by themuck** [comment]
aaa it works now, my mistake :)

**Comment by richardbarnett** [comment]
Ok then! Glad it's working for you.

**Comment by themuck** [comment]
thanks, must i calibrate the gyros and Accel sensor to?
