### ISSUE TITLE
Got gibberish in serial monitor using RTArduLinkIMU and would stop in few seconds.

### ISSUE THREAD

**Issue by YangWH** [richards-tech/RTIMULib-Arduino#20]
Hi,

I am trying RTArduLinkIMU, but I got gibberish as below, and updating would stop in few seconds.
http://ppt.cc/ZPi7
Did I do anything wrong? 
I am using Arduino pro mini 5V,16M,ATmega328 + MPU6050 + HMC5883

Best.

**Comment by richardbarnett** [comment]
What are you trying to do? RTArduLink drives binary data to software such as RTHostIMU. If you want something that you can look at, try ArduinoIMU.

**Comment by YangWH** [comment]
Thanks for you instruction, I tried ArduinoIMU.
But updating still stop in few seconds.
I can't figure out what's going on there.
Do you have any idea?
Best.

**Comment by richardbarnett** [comment]
Actually no. You could try looking at the I2C signals with a scope to see if there's anything funny there. What kind of wiring to the IMU are you using?

**Comment by maziarzamani** [comment]
I have checked the I2C data. They are clean and i have tried to underclock the speed to double-check that as well.

I am using SPI from µC to IMU (500KHz).

Cheers
Maziar

**Comment by YangWH** [comment]
I don't have scope to check now. But I think it might cause by both 3.3V and 5V on I2C bus. I simply add a resistor on the bus and it works fine. I will try level shifter later. Thanks a lot for your great help!

**Comment by richardbarnett** [comment]
Excellent.
