### ISSUE TITLE
Is there a way to reset the heading values at some point?

### ISSUE THREAD

**Issue by isaacdrafton** [richards-tech/RTIMULib-Arduino#23]
Hi Richard,
I'm using an MINI-Imu v9 with the magnetometer disabled, So every time I start the IMU, the heading is around 0.

Is there a way or function which I can use to reset at any point this initial heading? 
E.g. To start fresh at any time if the IMU has moved and the yaw value is any value.

Best,
Isaac

**Comment by richardbarnett** [comment]
If you just want to reset it to zero, you could call fusion.reset(). Would that work for you?

**Comment by isaacdrafton** [comment]
Yes. Thanks!
